[package]
name = "rfactor-python"
version = "0.1.0"
authors = ["Gaëtan Cassiers <gaetan.cassiers@gmail.com>"]

[lib]
name = "rfactor_python"
crate-type = ["cdylib"]


[dependencies]
rfactor-lib = { path = "../rfactor-lib" }

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]

