[package]
name = "rfactor"
version = "0.1.0"
authors = ["Gaëtan Cassiers <gaetan.cassiers@gmail.com>"]

[lib]
name = "rfactor_python"
crate-type = ["cdylib"]

[dependencies]
structopt = "0.2"

[dependencies.cpython]
version = "0.1"
features = ["extension-module"]

